PROJECT_DISPLAY_NAME='GoinfrePM'
PROJECT_COMMAND='gpm'
PROJECT_MODULE='goinfre_pm'
PROJECT_SLUG='goinfre-pm'
PROJECT_AUTHOR='veer'
PROJECT_REPOSITORY='https://github.com/1-veer/goinfre-pm'
PROJECT_VERSION='1.1.0'
